# SPDX-FileCopyrightText: © 2025 SBT Localization https://sbt.localization.com.ua
# SPDX-FileContributor: Serhii Olendarenko <sergey.olendarenko@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-only

[Input]
bam = "original/CGATTR.BAM"

[InputMos]
# 2011 = "original/mos2011.PNG"
2011 = "../../override/mos2011.PNG"  # use the file created on the previous step instead of the original

[NewFrames]
0 = "ukr/Frame0.png"
1 = "ukr/Frame1.png"
2 = "ukr/Frame2.png"
3 = "ukr/Frame3.png"
4 = "ukr/Frame4.png"
5 = "ukr/Frame5.png"

[Output]
extract = "../../dump/cgattr"
update = "../../override"
