# SPDX-FileCopyrightText: © 2025 SBT Localization https://sbt.localization.com.ua
# SPDX-FileContributor: Serhii Olendarenko <sergey.olendarenko@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-only

[Input]
bam = "original/STARTBUT.BAM"

[InputMos]
2000 = "original/mos2000.PNG"
2001 = "original/mos2001.PNG"
2002 = "original/mos2002.PNG"
2003 = "original/mos2003.PNG"
2004 = "original/mos2004.PNG"
2005 = "original/mos2005.PNG"
2006 = "original/mos2006.PNG"
2007 = "original/mos2007.PNG"
2008 = "original/mos2008.PNG"
2009 = "original/mos2009.PNG"
2010 = "original/mos2010.PNG"
2011 = "original/mos2011.PNG"

[NewFrames]
0 = "ukr/STARTBUT00000.png"
1 = "ukr/STARTBUT00001.png"
2 = "ukr/STARTBUT00002.png"
3 = "ukr/STARTBUT00003.png"
4 = "ukr/STARTBUT00004.png"
5 = "ukr/STARTBUT00005.png"
6 = "ukr/STARTBUT00006.png"
7 = "ukr/STARTBUT00007.png"
8 = "ukr/STARTBUT00008.png"
9 = "ukr/STARTBUT00009.png"
10 = "ukr/STARTBUT00010.png"
11 = "ukr/STARTBUT00011.png"
12 = "ukr/STARTBUT00012.png"
13 = "ukr/STARTBUT00013.png"
14 = "ukr/STARTBUT00014.png"
15 = "ukr/STARTBUT00015.png"
16 = "ukr/STARTBUT00016.png"
17 = "ukr/STARTBUT00017.png"
18 = "ukr/STARTBUT00018.png"
19 = "ukr/STARTBUT00019.png"
20 = "ukr/STARTBUT00020.png"
21 = "ukr/STARTBUT00021.png"
22 = "ukr/STARTBUT00022.png"
23 = "ukr/STARTBUT00023.png"

[Output]
extract = "../../dump/startbut"
update = "../../override"
